# fly.toml app configuration file generated for phonebook-serkan on 2025-01-17T23:52:44+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-serkan'
primary_region = 'arn'

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
